# -*- coding: utf-8 -*-
"""RenameImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seK4DSoxPjAkXu090lulbG1AxDO00qQv

# RENAME IMAGE

The purpose of this processing which is numerical for each dataset and add the alphabet infront of the number.

**IMPORT LIBRARY**
"""

import os

"""**Processing**

folder = Target file

prefix = Setup the alphabet that infront of the number.
"""

folder = "C:/Users/PC19/Desktop/Data/NORMAL"
prefix = "n"

folder = "C:/Users/PC19/Desktop/Data/BENIGN"
prefix = "b"

folder = "C:/Users/PC19/Desktop/Data/MALIGNANT"
prefix = "m"

files = sorted(os.listdir(folder))

for i, file in enumerate(files, start=1):
    new_name = f"{prefix}{i:04d}.jpg"
    os.rename(
        os.path.join(folder, file),
        os.path.join(folder, new_name)
    )