# -*- coding: utf-8 -*-
"""VGG16_RemoveBG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8zr_zJkyOfXxhi_epiEZU-zfrzneBRb

# VGG 16 MODEL(CBIS-DDSM(REMOVE BACKGROUND))
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt

from google.colab import drive
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.utils.class_weight import compute_class_weight

vgg_base = VGG16(weights='imagenet', include_top=False, input_shape=(256, 256, 3))

vgg_base.trainable = False

x = GlobalAveragePooling2D()(vgg_base.output)

x = Dense(256, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.4)(x)

x = Dense(64, activation='relu')(x)
x = Dropout(0.2)(x)

predictions = Dense(1, activation='sigmoid')(x)

"""**DEFINE DATASET(Reove background CBIS-DDSM dataset
) PATH**
"""

base_dataset = "/content/drive/MyDrive/DDSMset_Cleaned"

img_size = (256, 256)
batch_size = 12

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2,
    rotation_range=12,
    width_shift_range=0.08,
    height_shift_range=0.08,
    zoom_range=0.12,
    horizontal_flip=False,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    base_dataset,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='binary',
    subset='training'
)

val_generator = val_datagen.flow_from_directory(
    base_dataset,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='binary',
    subset='validation',
    shuffle=False
)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_generator.classes),
    y=train_generator.classes
)

class_weights = dict(enumerate(class_weights))
print("Class Weights:", class_weights)

lr_scheduler = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    verbose=1,
    min_lr=1e-6
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

vgg_model = Model(inputs=vgg_base.input, outputs=predictions)

vgg_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy', 'auc', 'precision', 'recall']
)

vgg_history = vgg_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    class_weight=class_weights,
    callbacks=[lr_scheduler, early_stop]
)

vgg_model.save("/content/drive/MyDrive/VGG16phase1_DDSM_cleaned.h5")
print("Model saved successfully")

for layer in vgg_base.layers[-4:]:
    layer.trainable = True

vgg_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy', 'auc', 'precision', 'recall']
)

fine_tune_history = vgg_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    class_weight=class_weights,
    callbacks=[lr_scheduler, early_stop]
)

vgg_model.save("/content/drive/MyDrive/VGG16phase2_DDSM_cleaned.h5")
print("Model saved successfully")

# predictions
pred_probs = vgg_model.predict(val_generator)
pred_labels = (pred_probs > 0.5).astype(int)

# true labels
true_labels = val_generator.classes

print(classification_report(true_labels, pred_labels))
print(confusion_matrix(true_labels, pred_labels))

pred_labels = (pred_probs > 0.4).astype(int)

cm = confusion_matrix(true_labels, pred_labels)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign','Malignant'],
            yticklabels=['Benign','Malignant'])

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

plt.figure(figsize=(12,4))

# Accuracy
plt.subplot(1,2,1)
plt.plot(vgg_history.history['accuracy'], label='Train Accuracy')
plt.plot(vgg_history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1,2,2)
plt.plot(vgg_history.history['loss'], label='Train Loss')
plt.plot(vgg_history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

acc = vgg_history.history['accuracy'] + fine_tune_history.history['accuracy']
val_acc = vgg_history.history['val_accuracy'] + fine_tune_history.history['val_accuracy']

loss = vgg_history.history['loss'] + fine_tune_history.history['loss']
val_loss = vgg_history.history['val_loss'] + fine_tune_history.history['val_loss']

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(acc,label='Train Accuracy')
plt.plot(val_acc,label='Val Accuracy')
plt.legend()
plt.title("Accuracy")

plt.subplot(1,2,2)
plt.plot(loss,label='Train Loss')
plt.plot(val_loss,label='Val Loss')
plt.legend()
plt.title("Loss")

plt.show()

fpr, tpr, _ = roc_curve(true_labels, pred_probs)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, label='AUC = %0.2f' % roc_auc)
plt.plot([0,1],[0,1],'--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

vgg_model.summary()

K.clear_session()