# -*- coding: utf-8 -*-
"""Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPXALG4mebwskox9nT4b6faXZhzJrgYm

# Data Cleaning

**CONNECTING GOOGLE DRIVE**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**IMPORT LIBRARY**"""

import os
import numpy as np
import matplotlib.pyplot as plt
import cv2
import shutil
import pandas as pd

"""# CBIS-DDSM (DDSMset)

**Set Path**

CSV_PATH = CSV file

IMAGE_BASE_DIR = Image Source

TARGET_BASE_DIR = New target file
"""

CSV_PATH = "/content/drive/MyDrive/k_CBIS-DDSM/mass_case(with_jpg_img).csv"

IMAGE_BASE_DIR = "/content/drive/MyDrive/k_CBIS-DDSM"
TARGET_BASE_DIR = "/content/drive/MyDrive/DDSMset"

"""**READ CSV FILE**"""

df = pd.read_csv(CSV_PATH)

"""**CREATE FOLDER**

Create the sub-folder in target file (DDSMset):



*   BENIGN
*   NORMAL
*   MALIGNANT



"""

os.makedirs(f"{TARGET_BASE_DIR}/BENIGN", exist_ok=True)
os.makedirs(f"{TARGET_BASE_DIR}/NORMAL", exist_ok=True)
os.makedirs(f"{TARGET_BASE_DIR}/MALIGNANT", exist_ok=True)

"""Read image path and pathology labels from the CSV file. After that, copy each image into each class folder (BENIGN, MALIGNANT and NORMAL)

Organizing the dataset by reading each record depending column CSV file, then locating the mammogram image and copying it into the corresponding output folder based on pathology label.

New file is created using the row index:


*   MALIGNANT
*   BENIGN
*   NORMAL

Besides, there will print the copied image to avoid duplicate the image into the target dataset.
"""

copied = 0
missing = 0

for idx, row in df.iterrows():
    src = os.path.join(
        "/content/drive/MyDrive/k_CBIS-DDSM",
        row["jpg_fullMammo_img_path"]
    )

    pathology = row["pathology"]

    if pathology == "MALIGNANT":
        dst_dir = "/content/drive/MyDrive/DDSMset/MALIGNANT"
    elif pathology == "BENIGN":
        dst_dir = "/content/drive/MyDrive/DDSMset/BENIGN"
    elif pathology == "BENIGN_WITHOUT_CALLBACK":
        dst_dir = "/content/drive/MyDrive/DDSMset/NORMAL"
    else:
        continue

    os.makedirs(dst_dir, exist_ok=True)

    if os.path.exists(src):
        filename = os.path.basename(src)

        new_filename = f"{idx}_{filename}"

        shutil.copy(
            src,
            os.path.join(dst_dir, new_filename)
        )
        copied += 1
    else:
        missing += 1

print("Copied images:", copied)
print("Missing images:", missing)

"""# EXTRA DATASET

**Set Path**

source_ = Data Source

target_ = Target file
"""

source_normal = "/content/drive/MyDrive/Subset1/birads1"
source_benign = "/content/drive/MyDrive/Subset1/birads3/king_birads3"
source_malignant = [
    "/content/drive/MyDrive/Subset1/birads4",
    "/content/drive/MyDrive/Subset1/birads5"
]

target_normal = "/content/drive/MyDrive/Subset_cleaned1/normal"
target_benign = "/content/drive/MyDrive/Subset_cleaned1/benign"
target_malignant = "/content/drive/MyDrive/Subset_cleaned1/malignant"

"""**CREATE FOLDER**

Develop sub-folder inside the target file.

*   normal
*   benign
*   malignant



"""

os.makedirs(target_normal, exist_ok=True)
os.makedirs(target_benign, exist_ok=True)
os.makedirs(target_malignant, exist_ok=True)

"""**COPY IMAGE**

Copy image into the target file.
"""

# Copy NORMAL
for img in os.listdir(source_normal):
    shutil.copy(
        os.path.join(source_normal, img),
        target_normal
    )

# Copy BENIGN
for img in os.listdir(source_benign):
    shutil.copy(
        os.path.join(source_benign, img),
        target_benign
    )

# Copy MALIGNANT (BI-RADS 4 + 5)
for malignant_folder in source_malignant:
    for img in os.listdir(malignant_folder):
        shutil.copy(
            os.path.join(malignant_folder, img),
            target_malignant
        )